### ISSUE TITLE
时间测试，测试结果消失

### ISSUE THREAD

**Issue by mfjiang** [IKende/WebApiBenchmark#11]
时间60秒测试，测试完统计结果消失

**Comment by beetlex-io** [comment]
https://github.com/IKende/WebApiBenchmark/blob/master/webapibenchmark.0.8.7.zip
修改显示状态切换

**Comment by mfjiang** [comment]
> https://github.com/IKende/WebApiBenchmark/blob/master/webapibenchmark.0.8.7.zip
> 修改显示状态切换

感谢
