### ISSUE TITLE
请求的Host头中丢失非默认的端口号？

### ISSUE THREAD

**Issue by yyjdelete** [IKende/WebApiBenchmark#7]
测试版本0.7

get http://localhost:5000/api/test
预期Host: localhost:5000
实际Host: localhost

请求压测，不走反向代理时，部分服务器(如aspnetcore)会拒绝此请求并返回400

仅协议默认端口http(80),https(443)应该被忽略

---
单服务器在Header中手动设置也不能成功, 因为`:`(冒号)会被转义#8

**Comment by beetlex-io** [comment]
0.8版已经解决，aspnetcore如果host信息不对也会有这情况

**Comment by yyjdelete** [comment]
@IKende 
试了下单次测试是正常的, 但压力测试是不是被~~改坏了~~? 现在收到的(单个)压测包都是这个样子的

更新: 试了下不含端口号的情况还是正常的, 只是有端口号的时候会重复发送第一行

![image](https://user-images.githubusercontent.com/1819074/55285053-13a14480-53b6-11e9-9845-f6f46b947dc1.png)

```
GET /api/MemTest/test/1 HTTP/1.1
GET /api/MemTest/test/1 HTTP/1.1
GET /api/MemTest/test/1 HTTP/1.1
GET /api/MemTest/test/1 HTTP/1.1
GET /api/MemTest/test/1 HTTP/1.1
Host: 127.0.0.1:8888
Content-Type: application/json


```
![image](https://user-images.githubusercontent.com/1819074/55285051-05ebbf00-53b6-11e9-9df3-b1540e53571b.png)

**Comment by beetlex-io** [comment]
@yyjdelete 
我测了一下是有问题，因为这部分重新修改过为了方便以后querystring和header引用函数或变量的功能。

**Comment by yyjdelete** [comment]
另外现在访问80端口是加了端口号的?

**Comment by beetlex-io** [comment]
@yyjdelete 
错手把80端口写成90..

**Comment by beetlex-io** [comment]
@yyjdelete 
0.8.2 修复以上问题
