### ISSUE TITLE
Header请求的值会被不正确的转义

### ISSUE THREAD

**Issue by yyjdelete** [IKende/WebApiBenchmark#8]
测试版本0.7

测试中一下Header的值被不正确的转义
:/, (空格);"'=+
常见示例:
Date头中包含:(冒号) (空格),(逗号)
content-type头包含/+(image/svg+xml)
Cookie头中包含=;(分号)

实际上, 根据更新后的RFC规范本身, Header值可以包含任何ASCII字符(不清楚%和`\0`之类的不可显示字符会不会转义). 
但实际上这里其实可以完全不处理转义, 一般人为设置的时候都不会有范围外的字符的, 即使有也可以人工转义设置.

See
----
https://tools.ietf.org/html/rfc2616#section-4.2
更新👇
https://tools.ietf.org/html/rfc7230#section-3.2.4

**Comment by beetlex-io** [comment]
是的，header值是被转议了

**Comment by beetlex-io** [comment]
0.8版已经解决
